## 1. ROOT CAUSE & TECHNICAL ANALYSIS  

`ttnn.sampling` builds the cumulative probability array in **FP32** and then draws a single random threshold to decide the next token.  
The threshold is currently generated by the device RNG as a **bfloat16** value, packed into a single 16‑bit word.  
Because bfloat16 has only 8‑bit mantissa, the uniform distribution is effectively quantised to **256** distinct values (0.0 → 1.0).  
In addition, the packing routine silently caps the value at `255/256 ≈ 0.9961`, so the threshold can never reach 1.0.  

Consequences:

| Issue | Effect on sampling |
|-------|--------------------|
| **Coarse grid** | Tokens with probability < 1/256 are never selected because the cumulative probability can never fall below the next grid point. |
| **Capping at 255/256** | Tokens whose cumulative probability is very close to 1.0 (e.g. 0.999) are never chosen, producing a hard upper bound on the tail. |
| **Wormhole/Blackhole** | Both architectures use the same RNG implementation, so the bias is present on both. |

The fix is to generate the threshold as an **FP32** uniform random number, keeping the full 23‑bit mantissa. The threshold is then compared against the FP32 cumulative probability without any packing or capping.  
No public API changes are required – the host code still calls `ttnn.sampling`, but the device kernel now produces an FP32 threshold.

---

## 2. SURGICAL CODE SOLUTION  

Below is a minimal, production‑ready patch that replaces the bfloat16 threshold generation with an FP32 one and updates the compute kernel accordingly.

> **File:** `ttnn/cpp/ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.cpp`  
> **File:** `ttnn/cpp/ttnn/operations/reduction/sampling/device/kernels/compute/sampling_compare.cpp`  
> **File:** `ttnn/cpp/ttnn/operations/reduction/sampling/device/sampling.cpp` (host side)

```diff
--- a/ttnn/cpp/ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.cpp
+++ b/ttnn/cpp/ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.cpp
@@
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/compute/sampling_threshold.hpp"
-#include "ttnn/operations/reduction/sampling/device/kernels/dataflow/sampling_threshold.hpp"
-#include "ttnn/

⚡ <i>GPT OSS 20B (Groq LPU (Free) • 2.13s • $0.00)</i>